# Generated by Django 4.0.1 on 2022-02-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('scan_id', models.AutoField(primary_key=True, serialize=False)),
                ('scan_name', models.CharField(max_length=100)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('scan_status', models.CharField(default='Scanning', editable=False, max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('vuln_list', models.TextField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vuln',
            fields=[
                ('vuln_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('vuln_name', models.CharField(max_length=100)),
                ('vuln_info', models.CharField(max_length=1000)),
                ('vuln_severity', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
