# Generated by Django 2.1.2 on 2021-12-30 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.CharField(max_length=100, unique=True)),
                ('scan_name', models.CharField(max_length=100)),
                ('scan_date', models.DateTimeField()),
                ('scan_status', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vuln',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_id', models.CharField(max_length=100, unique=True)),
                ('vuln_name', models.CharField(max_length=100)),
                ('vuln_info', models.CharField(max_length=1000)),
                ('vuln_severity', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='scan',
            name='vuln_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan.Vuln'),
        ),
    ]
