# Generated by Django 2.1.2 on 2021-12-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='vuln_id',
        ),
        migrations.RemoveField(
            model_name='vuln',
            name='vuln_id',
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_status',
            field=models.CharField(default='Scanning', editable=False, max_length=100),
        ),
    ]
