# Generated by Django 2.1.2 on 2022-01-03 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_auto_20211230_1004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scan',
        ),
        migrations.DeleteModel(
            name='Vuln',
        ),
    ]
